title: TTT Top 10
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.08422939
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#000000'
    - '#FEF7E3'
    - '#272620'
    - '#BB9F90'
    - '#C96E24'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "3 T's Top 10"
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7150537
layout_spectrum: 0.4802867
