name: "3 T's Top 10"
favicon: null
layout_spectrum: 0.75194
typography_spectrum: 0.13576
title: TTT Top 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc9f54'
    - '#7ca7b3'
    - '#c64543'
    - '#9d6969'
    - '#e8d1a6'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
