name: "3 T's Top 10"
favicon: null
layout_spectrum: 0.31688
typography_spectrum: 0.61498
title: TTT Top 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#fefe00'
    - '#b4bcc9'
    - '#8a460f'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
