name: "3 T's Top 10"
favicon: null
layout_spectrum: 0.76878
typography_spectrum: 0.13576
title: TTT Top 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e84a8'
    - '#f8e035'
    - '#edcb7d'
    - '#9dcbe4'
    - '#7e7a67'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
