name: "3 T's Top 10"
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61498
title: TTT Top 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#000000'
    - '#7c5f37'
    - '#568aaf'
    - '#a51800'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
